# yazi.toml

[manager]
show_hidden = true
show_symlink = true
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]

[log]
enabled = false

[plugin]
prepend_previewers = []
append_previewers = []
prepend_finders = []
append_finders = []

[select]
open_title = "Open with:"
open_list = []

[open]
rules = [
    { name = "*/", use = "open_dir" },
    { mime = "text/*", use = "text" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
    { mime = "application/pdf", use = "pdf" },
]

[plugin.example]
package = "https://github.com/Yazi-Rs/example-plugin"
